### ISSUE TITLE
Crash on 1.19.3

### ISSUE THREAD

**Issue by PaladinFallen** [Qendolin/map-compass#4]
Happened when pulling up a map on 1.19.3

[11:19:17] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoClassDefFoundError: net/minecraft/class_1160
	at com.qendolin.mapcompass.CompassRenderer.<clinit>(CompassRenderer.java:37) ~[map-compass-1.0.2+1.19.1.jar:?]
	at net.minecraft.class_759.handler$cko000$afterDraw(class_759.java:2203) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_3223(class_759.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_3231(class_759.java:247) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_3228(class_759.java:452) ~[client-intermediary.jar:?]
	at net.minecraft.class_759.method_22976(class_759.java:364) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.redirect$bkm000$iris$disableVanillaHandRendering(class_757.java:3609) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3172(class_757.java:800) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1114) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:864) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1193) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1160
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 17 more

**Comment by Qendolin** [comment]
Fixed: https://modrinth.com/mod/map-compass/version/1.0.2%2B1.19.3
